server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    # Límites de subida y temporales (Mantén esto que arreglamos antes)
    client_max_body_size 100M;
    client_body_temp_path /tmp/client_body;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    # --- NUEVA REGLA DE PROTECCIÓN ---
    # Si buscan imágenes, css o js que no existen, devolver 404 directo.
    # No pasar la petición a index.php
    location ~ \.(ico|css|js|gif|jpeg|jpg|png|woff|ttf|otf|svg|woff2|eot|pdf)$ {
        try_files $uri $uri/ =404;
        access_log off;
        expires max;
    }
    # ---------------------------------

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Tiempos de espera
        fastcgi_read_timeout 300;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
    }
}